### ISSUE TITLE
Incorrect link for documentation

### ISSUE THREAD

**Issue by dneyirp** [mattupstate/flask-security#596]
Hi. The current README file and links at https://pypi.python.org/pypi/Flask-Security point to old documentation. This can be easily rectified by simply changing the documentation links to http://flask-security.readthedocs.io/en/latest/.

**Comment by jirikuncar** [comment]
The link has been fixed. Thank you!

**Comment by dneyirp** [comment]
Hi Jirikuncar

It is partially fixed. Only the first link on the page for Documentation is fixed, the second one is not.

**Comment by jirikuncar** [comment]
@dneyirp can you point me to the code where it should be fixed? Thank you

**Comment by dneyirp** [comment]
Hi Jiri

On this page: https://pypi.python.org/pypi/Flask-Security

First domentation link below the word “Resources” is fixed
but the other one below the “Author: Matt Wright” is still pointing to the pythonhosted.org site.

Wrong link for “Documentation: Flask-Security package documentation” line.

Till later

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by jirikuncar** [comment]
@dneyirp the https://pypi.python.org/pypi/Flask-Security will be fixed with new release.
